(define (problem blockProblem)
    (:domain blockWorld)
    (:objects A B C D - block)
    (:init  (clear B)
            (clear C) 
            (ontable A)
            (ontable D)
            (on B A)
            (on C D)
            (handempty))
    (:goal (and 
            (clear A) 
            (on A B) 
            (on B C) 
            (on C D) 
            (handempty) 
            (ontable D)
            )
    )
)